server.port: 8082

spring.cloud.stream.bindings:
  input:
    destination: json-person
    content-type: text/plain
    consumer.headerMode: raw
    group: processor-consumer
  output:
    destination: avro-person
    content-type: application/*+avro

# required for deserializing from avro-perosn topic
# spring.coud.stream.schema.avro.readerSchema: person.avsc

spring.cloud.stream.schema-registry-client.endpoint: http://localhost:8990/
schema.id: 1
